In [131]:
import config
import pandas as pd
from datetime import datetime
import alpaca_trade_api as tradeapi

# time in RFC-3339 format

api = tradeapi.REST(config.API_KEY,config.API_SECRET,base_url=config.API_URL)
# start 1 min before 
start = 'T'.join(str(datetime(2022, 11, 2, 14, 30, 15)).split(' ')) + 'Z'
# start 1 min after 
end = 'T'.join(str(datetime(2022, 11, 2, 15, 16, 25)).split(' ')) + 'Z'
barsets = api.get_bars(['SPY'],'1Min',start,end)

In [132]:
df = pd.DataFrame([[datetime.strptime(b['t'], '%Y-%m-%dT%H:%M:%SZ'),
                    b['o'],
                    b['h'],
                    b['l'],
                    b['c'],
                    b['v'],
                    b['vw'],
                    b['n']] for b in barsets._raw])
df.columns = ['Date','Open', 'High', 'Low', 'Close', 'Volume','Avg','Num']
display(df)

,Date,Open,High,Low,Close,Volume,Avg,Num
0,2022-11-02 14:31:00,382.3900,382.4100,382.1900,382.2700,61730,382.266002,678
1,2022-11-02 14:32:00,382.2700,382.3300,382.1800,382.1900,297993,384.230370,590
2,2022-11-02 14:33:00,382.1800,382.4250,382.1626,382.3900,67421,382.275083,831
3,2022-11-02 14:34:00,382.3801,382.4399,382.3200,382.3900,76192,382.392274,727
4,2022-11-02 14:35:00,382.3800,382.3913,382.1500,382.1800,58450,382.244693,775
5,2022-11-02 14:36:00,382.1800,382.4500,382.1800,382.3300,89710,382.342915,1054
6,2022-11-02 14:37:00,382.3300,382.4962,382.3200,382.4800,92116,382.407029,822
7,2022-11-02 14:38:00,382.4700,382.5900,382.2750,382.4500,138755,382.468046,1258
8,2022-11-02 14:39:00,382.4600,382.5700,382.3700,382.4600,139097,382.471018,939
9,2022-11-02 14:40:00,382.4900,382.5700,382.4201,382.4950,87237,382.489382,759
10,2022-11-02 14:41:00,382.4500,382.4700,382.3700,382.4600,45639,382.415902,500
11,2022-11-02 14:42:00,382.4500,382.4982,382.2600,382.4000,64176,382.372952,740
12,2022-11-02 14:43:00,382.3900,382.6300,382.3600,382.5701,83275,382.518408,811
13,2022-11-02 14:44:00,382.5800,382.7300,382.5200,382.5600,81716,382.610413,790
14,2022-11-02 14:45:00,382.5700,382.7650,382.5100,382.7600,89133,382.630330,756
15,2022-11-02 14:46:00,382.7500,382.7600,382.6100,382.6500,78329,382.699047,843
16,2022-11-02 14:47:00,382.6301,382.8476,382.6301,382.8200,341519,384.112451,962
17,2022-11-02 14:48:00,382.8050,382.8050,382.6200,382.6301,70591,382.723101,699
18,2022-11-02 14:49:00,382.6400,382.7800,382.6300,382.6800,51417,382.704157,630
19,2022-11-02 14:50:00,382.6600,382.7000,382.4800,382.4900,61364,382.567775,650
20,2022-11-02 14:51:00,382.4900,382.6667,382.4200,382.6400,75095,382.523001,883
21,2022-11-02 14:52:00,382.6365,382.8200,382.5100,382.8001,55977,382.638452,688
22,2022-11-02 14:53:00,382.8000,382.9500,382.7500,382.8100,77775,382.854283,798
23,2022-11-02 14:54:00,382.8000,383.1200,382.8000,383.0400,108611,382.966194,1029
24,2022-11-02 14:55:00,383.0200,383.1000,382.9500,383.0600,72174,383.021770,708
25,2022-11-02 14:56:00,383.0800,383.1000,382.9400,383.0400,374745,384.079632,1114
26,2022-11-02 14:57:00,383.0500,383.0600,382.9450,383.0200,57551,383.014296,685
27,2022-11-02 14:58:00,383.0400,383.1000,383.0000,383.0300,49596,383.053667,576
28,2022-11-02 14:59:00,383.0400,383.0450,382.6950,382.7500,92366,382.859717,874
29,2022-11-02 15:00:00,382.7600,383.0050,382.7400,382.9500,85940,382.898173,890
30,2022-11-02 15:01:00,382.9500,383.0700,382.8450,382.9452,85198,382.978429,665
31,2022-11-02 15:02:00,382.9350,383.0200,382.8550,382.8600,104481,382.936559,876
32,2022-11-02 15:03:00,382.8600,382.9500,382.8100,382.8600,58906,382.872623,626
33,2022-11-02 15:04:00,382.8900,382.9500,382.7899,382.8050,77154,382.868716,663
34,2022-11-02 15:05:00,382.8100,383.0300,382.8100,382.8500,56242,382.897168,687
35,2022-11-02 15:06:00,382.8450,382.8700,382.7200,382.7200,306569,384.275510,551
36,2022-11-02 15:07:00,382.7300,382.8600,382.7001,382.8150,51370,382.774593,532
37,2022-11-02 15:08:00,382.8200,382.8600,382.6600,382.6917,52963,382.765334,618
38,2022-11-02 15:09:00,382.6801,382.8600,382.6801,382.8400,45988,382.800721,416
39,2022-11-02 15:10:00,382.8100,382.8700,382.6600,382.6700,72188,382.729240,538
40,2022-11-02 15:11:00,382.6800,382.8700,382.6300,382.8100,44972,382.764355,585
41,2022-11-02 15:12:00,382.7900,382.9300,382.6650,382.6699,70182,382.830936,796
42,2022-11-02 15:13:00,382.6699,382.6700,382.4200,382.5200,86683,382.530562,817
43,2022-11-02 15:14:00,382.5200,382.5700,382.4221,382.4600,53192,382.491807,556
44,2022-11-02 15:15:00,382.4500,382.5000,382.3720,382.4000,46982,382.428776,548
45,2022-11-02 15:16:00,382.3800,382.4200,382.2700,382.3450,112347,382.356938,924

In [133]:
df.to_csv('spy.csv',index =False)

```
t	string/timestamp	Timestamp in RFC-3339 format with nanosecond precision
o	number	Open price
h	number	High price
l	number	Low price
c	number	Close price
v	int	Volume
n	int	Number of trades
vw	number	Volume-weighted average price
```

In [124]:
'Open,High,Low,Close,Volume'.split(',')

['Open', 'High', 'Low', 'Close', 'Volume']