In [1]:
import pandas as pd
import base64
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [21]:
year = 2022
url = f"https://www.basketball-reference.com/leagues/NBA_{year}_per_game.html"
html = pd.read_html(url, header=0)
df = html[0]
raw = df.drop(df[df['Age'] == 'Age'].index)
raw = raw.fillna(0)
playerstats = raw.drop(['Rk'], axis=1)
playerstats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Precious Achiuwa,C,22,TOR,73,28,23.6,3.6,8.3,.439,...,.595,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1
1,Steven Adams,C,28,MEM,76,75,26.3,2.8,5.1,.547,...,.543,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9
2,Bam Adebayo,C,24,MIA,56,56,32.6,7.3,13.0,.557,...,.753,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1
3,Santi Aldama,PF,21,MEM,32,0,11.3,1.7,4.1,.402,...,.625,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1
4,LaMarcus Aldridge,C,36,BRK,47,12,22.3,5.4,9.7,.550,...,.873,1.6,3.9,5.5,0.9,0.3,1.0,0.9,1.7,12.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,5.5,.465,...,.481,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3
838,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,.460,...,.904,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4
839,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,.526,...,.623,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3
840,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,.567,...,.776,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2
841,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,6.5,.626,...,.727,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3

In [18]:
def load_data(year):
    url = f"https://www.basketball-reference.com/leagues/NBA_{year}_per_game.html"
    html = pd.read_html(url, header=0)
    df = html[0]
    raw = df.drop(df[df['Age'] == 'Age'].index)
    raw = raw.fillna(0)
    playerstats = raw.drop(['Rk'], axis=1)
    return playerstats

In [31]:
f"C,PF,SF,PG,SG".split(',')

['C', 'PF', 'SF', 'PG', 'SG']

In [44]:
list(playerstats['Pos'].unique())

['C',
 'PF',
 'SG',
 'PG',
 'SF',
 'SG-PG',
 'SG-SF',
 'PG-SG',
 'SF-SG',
 'PF-SF',
 'C-PF',
 'PF-C',
 'SG-PG-SF']

In [19]:
url = f"https://www.pro-football-reference.com/years/2022/rushing.htm"
html = pd.read_html(url, header=1)
df = html[0]
raw = df.drop(df[df['Age'] == 'Age'].index)
raw = raw.fillna(0)
playerstats = raw.drop(['Rk'], axis=1)
playerstats

,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
0,Derrick Henry *,TEN,28,RB,15,15,319,1429,13,64,56,4.5,95.3,6
1,Josh Jacobs*,LVR,24,RB,15,15,306,1539,11,86,86,5.0,102.6,3
2,Saquon Barkley*,NYG,25,RB,15,15,283,1254,10,60,68,4.4,83.6,1
3,Nick Chubb*,CLE,27,RB,15,15,276,1344,12,61,41,4.9,89.6,1
4,Dalvin Cook,MIN,27,RB,15,15,244,1109,8,47,81,4.5,73.9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,Courtland Sutton,DEN,27,WR,13,13,1,5,0,0,5,5.0,0.4,0
345,Deven Thompkins,TAM,23,WR,3,0,1,9,0,0,9,9.0,3.0,1
346,Marquez Valdes-Scantling,KAN,28,WR,15,9,1,-3,0,0,-3,-3.0,-0.2,0
347,Cedrick Wilson Jr.,MIA,27,WR,14,0,1,8,0,0,8,8.0,0.6,0
348,Michael Woods II,CLE,22,WR,8,0,1,-5,0,0,-5,-5.0,-0.6,0

In [5]:
for h in html:
    display(h)

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
0,1,Derrick Henry *,TEN,28,RB,15,15,319,1429,13,64,56,4.5,95.3,6
1,2,Josh Jacobs*,LVR,24,RB,15,15,306,1539,11,86,86,5.0,102.6,3
2,3,Saquon Barkley*,NYG,25,RB,15,15,283,1254,10,60,68,4.4,83.6,1
3,4,Nick Chubb*,CLE,27,RB,15,15,276,1344,12,61,41,4.9,89.6,1
4,5,Dalvin Cook,MIN,27,RB,15,15,244,1109,8,47,81,4.5,73.9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,334,Courtland Sutton,DEN,27,WR,13,13,1,5,0,0,5,5.0,0.4,0
345,335,Deven Thompkins,TAM,23,WR,3,0,1,9,0,0,9,9.0,3.0,1
346,336,Marquez Valdes-Scantling,KAN,28,WR,15,9,1,-3,0,0,-3,-3.0,-0.2,0
347,337,Cedrick Wilson Jr.,MIA,27,WR,14,0,1,8,0,0,8,8.0,0.6,0
348,338,Michael Woods II,CLE,22,WR,8,0,1,-5,0,0,-5,-5.0,-0.6,0

In [22]:
html[0].Tm.unique()

array(['TOR', 'MEM', 'MIA', 'BRK', 'TOT', 'NOP', 'UTA', 'MIL', 'CLE',
       'IND', 'LAL', 'ORL', 'NYK', 'HOU', 'WAS', 'Tm', 'PHO', 'SAC',
       'DET', 'CHO', 'CHI', 'ATL', 'DEN', 'PHI', 'SAS', 'LAC', 'OKC',
       'MIN', 'DAL', 'GSW', 'POR', 'BOS'], dtype=object)

In [25]:
f"Passing,Rushing,Receiving,Scrimmage Stats,Defense,Kicking,Punting,Kick & Punt Returns,Scoring".split(',')

['passing',
 'rushing',
 'receiving',
 'scrimmage stats',
 'defense',
 'kicking',
 'punting',
 'kick & punt returns',
 'scoring']